### ISSUE TITLE
Numerous issues with card generation for about us page 

### ISSUE THREAD

**Issue by JonathanOppenheimer** [apc-gmhs/apc-website#17]
-The Instagram CDN ripper code fails to work in some cases 
![Screen Shot 2020-04-14 at 12 46 13 PM](https://user-images.githubusercontent.com/12973114/79251294-f2d75000-7e4d-11ea-8add-5e9e871faff7.png)
-Some people who requested "the hamster"'s requests were not accounted for.

**Comment by DannyOppenheimer** [comment]
Fixed in commit 09874f29b419cb5ce9fcb9c8741a542f3af56e24
