### ISSUE TITLE
Link JavaScript in a consistent way from the bottom of the file

### ISSUE THREAD

**Issue by ErikBoesen** [apc-gmhs/apc-website#21]
Right now <script> tags linking page-specific JS files are interspersed throughout the document. It might be nice to just add a page property that lists custom scripts needed, that way you can simply add 
```
scripts:
- about_us
```
to the YML frontmatter of the page instead of sticking a script tag in. It looks like you do this elsewhere so it should be a simple fix.

**Comment by AndrewLester** [comment]
Fixed recently
