### ISSUE TITLE
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

### ISSUE THREAD

**Issue by JonathanOppenheimer** [apc-gmhs/apc-website#3]
the navbar color isn't right there's a white border around everything and the https is fricked aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

i cant fix any of it
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by JonathanOppenheimer** [comment]
i was dum - peep the TO_DO

**Comment by AndrewLester** [comment]
We should move the TODO into separate issues
