### ISSUE TITLE
Add scrolling animation to links directed at a compendium entry with URL hash

### ISSUE THREAD

**Issue by JonathanOppenheimer** [apc-gmhs/apc-website#39]
It'd be advantageous if we could link to specific compendium entries through the URL 

For example, https://apc-gm.com/compendium#16-10-20 could/would take you to the 4th compendium entry

**Comment by BrandonWerbel** [comment]
This actually is possible, just add the name of the div after a hashtag to the URL. For example, https://apc-gm.com/compendium#entry-2020-10-16 would be a direct link to the second to last entry.

**Comment by JonathanOppenheimer** [comment]
Ah you're totally right - I think Andrew brought this up a while ago and it just totally slipped my mind -- @AndrewLester IIRC you wanted to add an animation to scroll to that link format, I think? 

Great catch Brandon

**Comment by AndrewLester** [comment]
Yeah this does work as a solution, but I think it would be nice to see the scroll animation appear for even this kind of link. However, we could begin using links that include the hash for a specific entry in preparation for a change to add the scrolling animation.

One possible issue is that the scrolling animation may be overridden by the automatic position from the url hash.
